'reinit'
'open D:\untuk_nwp1\script\D3_1.ctl'
'set t 1 40'
'set lat -6.25'
'set lon 106.76'
'set timelab off'
'set grads off'
'set grid off'
'set gxout line'
'set ccolor 4'
'set line 6'
'd rainc+rainnc'
'draw ylab Curah Hujan (mm)'
'draw xlab Waktu (UTC)'
'draw title Curah Hujan 07 November 2021 (UTC)'
'printim D:\untuk_nwp1\Hasil\CH_GRAFIK.png white'