'reinit'
'open D:\untuk_nwp1\script\D2_1.ctl'
'set timelab off'
'set grads off'
'set grid off'
'set gxout shaded'
'set mpdset mres'
'set csmooth on'
'd rainc+rainnc'
'basemap O 0 0 M'
'cbarn'
'draw ylab Lintang'
'draw xlab Bujur'
'set strsiz 0.13'
'set string 1 bl 6 0'
'draw string 9.4 1 (mm)'
'draw title Curah Hujan 07 November 2021 (UTC)'
'printim D:\untuk_nwp1\Hasil\CH_TOTAL.png white'