'reinit'
'open D:\untuk_nwp1\script\D3_1.ctl'
'set z 1 19'
'set t 1 25'
'set lat -6.24'
'set lon 106.84'
'set grid off'
'set grads off'
'set timelab off'
'set csmooth on'
'set mpdset hires'
'set gxout shaded'
'set parea 1 9.3 1 8'
'd CLDFRA'
'cbarn'
'draw ylab Lapisan (mb)'
'draw xlab Waktu (UTC)'
'set strsiz 0.13'
'set string 1 bl 6 0'
'draw string 10 1.5 (%)'
'draw title Tutupan Awan 00-24 UTC 07 November 2021'
'printim D:\untuk_nwp1\Hasil\cloud_cover.png white'