'reinit'
'open D:\untuk_nwp1\script\D3_1.ctl'
'set z 1 19'
'set t 1 25'
'set lat -6.24'
'set lon 106.84'
'set grid off'
'set grads off'
'set timelab off'
'set gxout shaded'
'set mpdset hires'
'set csmooth on'
'd td'
'cbarn'
'draw ylab Lapisan (mb)'
'draw title Titik Embun 00-24 UTC 07 November 2021'
'printim D:\untuk_nwp1\Hasil\RH.png white'