'reinit'
'sdfopen E:/dataset.nc'
'q file'
'set z 1 27'
'set lat -3'
'set lon 98'
'd w'
'draw title Profil Vertical Velocity Kel. Tanjung Gusta 09/10/2021 03Z'
'draw xlab Vertical Velocity (Pa/s)'
'draw ylab Tekanan Udara (mb)'
'printim D:/ver_vel.png white'
