'reinit'
'open D:\untuk_nwp1\script\D3_1.ctl'
'set z 1 19'
'set t 1 25'
'define vort = hcurl(umet,vmet)'
'set lat -6.24'
'set lon 106.84'
'set grid off'
'set grads off'
'set timelab off'
'set csmooth on'
'set gxout shaded'
'set parea 1 9 1 8'
'd vort'
'cbarn'
'draw ylab Lapisan (mb)'
'draw xlab Waktu (UTC)'
'set strsiz 0.13'
'set string 1 bl 6 0'
'draw title Vortisitas 00-24 UTC 07 November 2021'
'printim D:\untuk_nwp1\Hasil\vortisitas.png white'